pub mod categories;
mod client;
mod common;
pub mod developers;
mod endpoint;
pub mod engines;
mod error;
pub mod games;
pub mod gametypes;
pub mod genres;
pub mod guests;
pub mod leaderboards;
pub mod levels;
pub mod notifications;
mod pagination;
pub mod platforms;
pub mod profile;
pub mod publishers;
mod query;
pub mod regions;
pub mod runs;
pub mod series;
pub mod users;
mod utils;
pub mod variables;

pub use client::{AsyncClient, Client, RestClient};
pub use common::{CategoriesSorting, Direction, VariablesSorting};
pub use error::ApiError;
pub use pagination::{Pageable, PagedEndpointExt, PagedIter, SinglePage, SinglePageBuilder};
pub use query::AsyncQuery;
